# Change these first
owner: thewilloftheshadow # Your GitHub username
repo: tckartwork # Your GitHub repository name

# Add your sites here
sites:
  - name: tckartwork.xyz
    url: https://www.tckartwork.xyz
  - name: Admin
    url: https://admin.tckartwork.xyz
    expectedStatusCodes:
      - 200
      - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tckartwork.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.tckartwork.xyz/profile.png
  name: tckartwork.xyz
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: mailto:webmaster@tckartwork.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees: # Users to assign downtime issues (optional)
  - thewilloftheshadow
